# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b369c27ebcc8a42081e2516f19e9022"
name = "Test"
application_url = "https://rehab-olympic-delicious-click.trycloudflare.com"
embedded = true
handle = "test-20673"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://rehab-olympic-delicious-click.trycloudflare.com/auth/callback", "https://rehab-olympic-delicious-click.trycloudflare.com/auth/shopify/callback", "https://rehab-olympic-delicious-click.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
