# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f65aead5a0ab1ede7307a55ac80c2610"
name = "Discount Request"
application_url = "https://demands-selection-toilet-changing.trycloudflare.com"
embedded = true
handle = "discount-request-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://demands-selection-toilet-changing.trycloudflare.com/auth/callback", "https://demands-selection-toilet-changing.trycloudflare.com/auth/shopify/callback", "https://demands-selection-toilet-changing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
