
api_version = "2025-04"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "vbd-form-builder"
type = "ui_extension"
uid = "c4bf5f78-82a8-b1b8-0f45-baf73d194c41151fb4d4"

# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/BlockExtension.jsx"
target = "admin.product-details.block.render"


# Valid extension targets:

# Abandoned checkout detail page
# - admin.abandoned-checkout-details.block.render

# Collection detail pages
# - admin.collection-details.block.render

# Catalog detail page
# - admin.catalog-details.block.render

# Company detail page
# - admin.company-details.block.render
# - admin.company-location.block.render

# Customer detail page
# - admin.customer-details.block.render

# Draft order detail pages
# - admin.draft-order-details.block.render

# Gift card detail page
# - admin.gift-card-details.block.render

# Order detail page
# - admin.order-details.block.render

# Product detail pages
# - admin.product-details.block.render

# Product variant detail pages
# - admin.product-variant-details.block.render
